import type { IdentityCandidate, IdentityScanResult } from "@/types/identity";
import { buildClaimChecklist } from "@/lib/claimChecklist";

export function exportIdentityMarkdown(scan: IdentityScanResult, focus?: IdentityCandidate): string {
  const candidate = focus ?? scan.candidates[0];
  if (!candidate) {
    return `# Identity scan: ${scan.brandName}\n\nNo candidates returned.\n`;
  }

  const checklist = buildClaimChecklist(candidate);
  const lines = [
    `# Identity Lock: ${scan.brandName}`,
    ``,
    `**Tier:** ${scan.tier} options · **Scanned:** ${new Date(scan.scannedAt).toLocaleString()}`,
    `**Top pick:** ${candidate.label} (\`${candidate.slug}\`) — score ${candidate.score}/100`,
    ``,
    scan.meta.topPick ? `> ${scan.meta.topPick.rationale}` : "",
    ``,
    `## Score breakdown`,
    `- Consistency: ${candidate.scoreBreakdown.consistency}`,
    `- Pronounceability: ${candidate.scoreBreakdown.pronounceability}`,
    `- Domain coverage: ${candidate.scoreBreakdown.domainCoverage}`,
    `- Social coverage: ${candidate.scoreBreakdown.socialCoverage}`,
    `- TLD quality: ${candidate.scoreBreakdown.tldQuality}`,
    ``,
    `## Domains`,
    ...candidate.domains.map(
      (d) => `- \`${d.fqdn}\` — **${d.status}**${d.registrarHint ? ` (${d.registrarHint})` : ""}`
    ),
    ``,
    `## Social handles`,
    ...candidate.social.map(
      (s) =>
        `- **${s.platformName}** @${s.handle} — ${s.status}${s.note ? ` — ${s.note}` : ""}${s.claimUrl ? ` — [claim](${s.claimUrl})` : ""}`
    ),
    ``,
    `## Claim checklist`,
    ...checklist.map((step, i) => `${i + 1}. ${step}`),
    ``,
    `---`,
    `Generated by Archive Arac Identity Lock`,
  ];
  return lines.filter(Boolean).join("\n");
}
