import type { AnalysisResult } from "@/types/analysis";
import { recommendStrands } from "@/lib/strandMatcher";
import { scheduleVaultSync } from "@/lib/vaultSync";

const VAULT_KEY = "archive-arac:vault";
const MAX_ENTRIES = 24;

export interface VaultEntry {
  id: string;
  savedAt: string;
  label: string;
  result: AnalysisResult;
  strandIds: number[];
}

function readVault(): VaultEntry[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(VAULT_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as VaultEntry[];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function writeVault(entries: VaultEntry[]) {
  localStorage.setItem(VAULT_KEY, JSON.stringify(entries.slice(0, MAX_ENTRIES)));
}

export function listVault(): VaultEntry[] {
  return readVault().sort((a, b) => b.savedAt.localeCompare(a.savedAt));
}

export function saveToVault(result: AnalysisResult, label?: string): VaultEntry {
  const entry: VaultEntry = {
    id: crypto.randomUUID(),
    savedAt: new Date().toISOString(),
    label: label?.trim() || result.hostname,
    result,
    strandIds: recommendStrands(result).map((m) => m.strand.id),
  };
  const next = [entry, ...readVault().filter((e) => e.result.url !== result.url)];
  writeVault(next);
  scheduleVaultSync();
  return entry;
}

export function removeFromVault(id: string) {
  writeVault(readVault().filter((e) => e.id !== id));
  scheduleVaultSync();
}

export function getVaultEntry(id: string): VaultEntry | null {
  return readVault().find((e) => e.id === id) ?? null;
}

export function exportReportMarkdown(result: AnalysisResult): string {
  const strands = recommendStrands(result);
  const lines = [
    `# Silk Report: ${result.title}`,
    ``,
    `**URL:** ${result.url}`,
    `**Score:** ${result.overview.score}/100`,
    `**Vibe:** ${result.overview.vibe}`,
    ``,
    `## Summary`,
    result.overview.summary,
    ``,
    `## Tech`,
    `- Frameworks: ${result.tech.frameworks.join(", ") || "—"}`,
    `- Libraries: ${result.tech.libraries.join(", ") || "—"}`,
    `- Analytics: ${result.tech.analytics.join(", ") || "—"}`,
    ``,
    `## Recommended strands`,
    ...strands.map((m) => `- **${m.strand.name}** — ${m.reasons[0]}`),
    ``,
    `---`,
    `Generated by Archive Arac Silk Analyzer`,
  ];
  return lines.join("\n");
}
